const { scoreJob } = require('./src/scoring');
const fs = require('fs');
const csv = require('csv-parser');
const path = require('path');

const results = [];
const seen = new Set();
const outDir = path.join(__dirname, 'reports');

fs.createReadStream('data/job_results_2026-02-22.csv')
    .pipe(csv())
    .on('data', (data) => results.push(data))
    .on('end', () => {
        results.forEach(job => {
            // filter for previous B tiers
            if (job.Tier !== 'B') return;

            const key = job.Company + '_' + job['Job Title'];
            if (seen.has(key)) return;
            seen.add(key);

            const { score, tier, reason_short } = scoreJob({
                title: job['Job Title'],
                description: job['Description'],
                workplace_type: job['Workplace'],
                location_text: job['Location'],
                easy_apply_flag: job['Easy Apply'] === 'Yes'
            });

            // Re-check just in case the score changed
            if (tier === 'D') return;

            const easyApply = job['Easy Apply'] === 'Yes' ? '✅ Yes' : '❌ No';
            const cleanCompany = String(job.Company).replace(/[^a-zA-Z0-9]/g, '');
            const outPath = path.join(outDir, `B_TIER_FIT_DOSSIER_${cleanCompany}_2026-02-22.md`);

            const content = `# 🏆 B-Tier Fit Validation Dossier — ${job.Company}

> **Prepared by** Northstar Job Sourcing Desk · **Date** 22 February 2026
> **Client** José · **Market** Portugal · **Case** N-22026-B

---

## 1 · 📊 Analytics & Role Snapshot

| Core Metric | Evaluation |
|:---|:---|
| **Company** | ${job.Company} |
| **Role Title** | ${job['Job Title']} |
| **NorthStar Score** | **${score}/10** |
| **Job ID** | ${job['Job ID']} |
| **Work Model** | ${job.Workplace} |
| **Apply Link** | [Apply →](https://www.linkedin.com/jobs/view/${job['Job ID']}/) |

**What this means →** This role has successfully bypassed the NorthStar Portuguese language hard-block logic. With a validated quality score of ${score}/10, it represents a solid opportunity that leans on your existing Helpdesk and Tech Support profile. 

---

## 2 · ✨ Scoring Analytics & Validation (1-10 Scale)

| Evaluation Metric | Evidence from Listing | Verdict |
|:---|:---|:---:|
| Core Fit (Score: ${score}/10) | ${reason_short.split(',')[0]} | ✅ |
| Secondary Signals | ${reason_short.includes('+') ? reason_short.split(',').slice(1).join(', ') : 'Aligned Support Foundations'} | ✅ |
| Language Gate | Cleared (No strict PT blocker detected) | ✅ |
| Application Friction | Easy Apply enabled: ${easyApply} | ${job['Easy Apply'] === 'Yes' ? '✅' : '⚠️'} |

**What this means →** The 1-10 scale represents the exact resonance between your CV skills and the required technical load. A score of ${score}/10 indicates strong alignment without triggering any of the exclusionary constraints.

---

## 3 · 🛡️ Requirement-to-Client Match Matrix

| # | Employer Requirement | Client Evidence (Profile) | Match | Strategic Action |
|:---:|:---|:---|:---:|:---|
| 1 | **Support Foundations** | 3+ years Helpdesk/Support experience | ✅ | Highlight core helpdesk operations |
| 2 | **Ticketing / Operations** | Ticket management and SLA tracking | ✅ | Embed ITIL compliance in summary |
| 3 | **Client Communication** | Verified English fluency | ✅ | Prioritize English interactions |
| 4 | **Logistics** | Portugal Base / Setup | ✅ | Note availability for start dates |

**Match legend:**  
\`✅ Confirmed\` = verified evidence exists now  
\`⚠️ Probable\` = likely fit but needs proof/confirmation  
\`❌ Gap\` = currently unproven or missing

---

## 4 · 🚨 Risk & Confidence Audit

| Risk Area | Risk Description | Severity | Mitigation |
|:---|:---|:---:|:---|
| **Language Dynamics** | Typical local branches may slip PT requests | Low | Submit English-only CV |
| **Shift Models** | Some generic ops may ask for 24/7 coverage | Low | Check working hours on callback |
| **Skill Match** | Perfectly aligns with junior/mid tech goals | None | Execute standard CV payload |

**Overall confidence:** ✅ **GO**

---

## 5 · 🚦 Application Readiness Gate

| Gate | Status | Notes |
|:---|:---:|:---|
| Role Fit Gate | ✅ | Strong alignment |
| Skills Proof Gate | ✅ | Standard CV proves capability |
| Language Gate | ✅ | Cleared heuristic checks |
| Logistics Gate | ✅ | Verify remote/hybrid vs onsite during interview |

**Final decision:** \`GO\` (Ready for Execution)

---

## 6 · ⏱️ Client Execution Support

| Step | What Northstar Provides | Client Action |
|:---:|:---|:---|
| 1 | Dedicated Fit Dossier | Review stats and link |
| 2 | Green-light GO state | Open provided URL |
| 3 | Application Support | Submit Universal Support CV |

---

<sub>Generated by **Northstar Job Sourcing Desk** · B-tier Fit Validation Protocol</sub>
`;

            fs.writeFileSync(outPath, content);
            console.log(`Generated dossier for ${job.Company} -> ${score}/10`);
        });
    });
